// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcyrsygxvubmkksqzwzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjeXJzeWd4dnVibWtrc3F6d3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzMzNDksImV4cCI6MjA2NTQwOTM0OX0.WsHBmBj06gS4u4myrjbz2d7f4FYH0FUAAc_rZNO93HE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);